const assignNoteForCentral = (stationName) => {
  switch(stationName) {
    // case 'WestRuislip':
    //   return 'A1';
    // case 'RuislipGardens':
    //   return 'A2';
    // case 'SouthRuislip':
    //   return 'A3';
    // case 'Northolt':
    //   return 'A4';
    // case 'Greenford':
    //   return 'A5';
    // case 'Perivale':
    //   return 'A6';
    // case 'HangerLane':
    //   return 'A7';
    // case 'NorthActon':
    //   return 'A8';
    // case 'EastActon':
    //   return 'A9';
    // case 'WhiteCity':
    //   return 'A10';
    // case 'ShepherdsBush(Central)':
    //   return 'A11';
    // case 'HollandPark':
    //   return 'A12';
    // case 'NottingHillGate':
    //   return 'A13';
    // case 'Queensway':
    //   return 'A14';
    // case 'LancasterGate':
    //   return 'A15';
    // case 'MarbleArch':
    //   return 'A16';
    // case 'BondStreet':
    //   return 'A17';
    // case 'OxfordCircus':
    //   return 'A18';
    // case 'TottenhamCourtRoad':
    //   return 'A19';
    // case 'Holborn':
    //   return 'A20';
    // case 'ChanceryLane':
    //   return 'A21';
    // case 'St.Pauls':
    //   return 'A22';
    // case 'Bank':
    //   return 'A23';
    // case 'LiverpoolStreet':
    //   return 'A24';
    // case 'BethnalGreen':
    //   return 'A25';
    // case 'MileEnd':
    //   return 'A26';
    // case 'Stratford':
    //   return 'A27';
    // case 'Leyton':
    //   return 'A28';
    // case 'Leytonstone':
    //   return 'A29';
    // case 'Wanstead':
    //   return 'A30';
    // case 'Redbridge':
    //   return 'A31';
    // case 'GantsHill':
    //   return 'A32';
    // case 'NewburyPark':
    //   return 'A33';
    // case 'Barkingside':
    //   return 'A34';
    // case 'Fairlop':
    //   return 'A35';
    // case 'Hainault':
    //   return 'A36';
    // case 'GrangeHill':
    //   return 'A37';
    // case 'Chigwell':
    //   return 'A38';
    // case 'RodingValley':
    //   return 'A39';
    // case 'Snaresbrook':
    //   return 'A40';
    // case 'SouthWoodford':
    //   return 'A41';
    // case 'Woodford':
    //   return 'A42';
    // case 'BuckhurstHill':
    //   return 'A43';
    // case 'Loughton':
    //   return 'A44';
    // case 'Debden':
    //   return 'A45';
    // case 'TheydonBois ':
    //   return 'A46';
    // case 'Epping':
    //   return 'A47';
    default:
      return 'C6';
    }
  }
  
  module.exports = assignNoteForCentral;
  